name: book_recommender
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=11.1
  - numpy=1.21.0
  - pandas=1.3.0
  - scikit-learn=0.24.2
  - matplotlib=3.4.2
  - seaborn=0.11.1
  - jupyterlab=3.0.16
  - notebook=6.4.0
  - flask=2.0.1
  - gunicorn=20.1.0
  - pytest=6.2.4
  - pylint=2.8.3
  - black
  - pip
  - pip:
    - torchsummary